{% set name = "handout" %}
{% set version = "1.1.2" %}
{% set sha256 = "52daaf1f9a4cb2ceb88c1dedf85d22ef449b9422b424a2534d21f941e57bc915" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - handout

about:
  home: "http://github.com/danijar/handout"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: "LICENSE-2.0.txt"
  summary: "Turn Python scripts into handouts with Markdown and figures"
  doc_url: "http://github.com/danijar/handout"
  dev_url: "http://github.com/danijar/handout"

extra:
  recipe-maintainers:
    - notestaff
