travis:
  secure:
    BINSTAR_TOKEN: ADddOX/Y7H7eP9/zJgztDGCZN9TMB/zvYOIa0URnzkUDmTxJNIVOblVrlJb576FbKW8Ravkiawdv28gS0pdtMHD2+p2mT/saqGw9/uE/lhhEPuU99NfxwDLoItQSzykRZcU2Blfe1ixf85DUurvEVH3Fxbe89EmPR4Xi/zT1X/b6Eo5jSfcpiwDZ7b3YtdgGUZffoG2N/kVP9kNrqMTmPIrDrPyQCyXC3Bp7nbU5q7t2McH5N5Sc8S7Vvm4GL5gh2Pr5oLvx77LqkTAgZbCIGUz/uOxClbKwmlPWsgxacXRBwhJyvVJ96kKqpwc7SgqPyXEOaoHPAceRNFzdLP9ZYZyj3yW54d35Oxw394voRLnAcy/Y5zLKbNW1JLsBQC9bZJ3SMwIA5T8jGBfkEx7xgJ8oHzQFT3iwDAIHkwTEchcA4xmgV1YWORHz+tqUcjyZ4mMCK3mWE/3q1yB8l+ZjEmeh1/mR2Om6uWJ5RXhRnZ3bKxjZ1HThM6EDIjltNMKheGCAC1YRZc8lq2ZLiHpaExGFSHmk1Gcf6TiOplFlosHOUIQWVIpGFCRR1DcjjghLNqV3Mz7dv2xqJ4vCGZeYjymNMvoaOPKHgm5obcionVVUvBHz6NX7rOjQyJnbspjlscDuWQNlxPuVtiwyhjkb7eRdnLfEVTzT35u0fr+qU3g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
